INSERT INTO brand (id, name, origin) VALUES
                                         (1, 'Audi', 'Đức'),
                                         (2, 'BMW', 'Đức'),
                                         (3, 'Chevrolet', 'Mỹ'),
                                         (4, 'Ford', 'Mỹ'),
                                         (5, 'Honda', 'Nhật Bản'),
                                         (6, 'Hyundai', 'Hàn Quốc'),
                                         (7, 'Isuzu', 'Nhật Bản'),
                                         (8, 'Kia', 'Hàn Quốc'),
                                         (9, 'Land Rover', 'Anh'),
                                         (10, 'Lexus', 'Nhật Bản'),
                                         (11, 'Mazda', 'Nhật Bản'),
                                         (12, 'Mercedes-Benz', 'Đức'),
                                         (13, 'Mitsubishi', 'Nhật Bản'),
                                         (14, 'Nissan', 'Nhật Bản'),
                                         (15, 'Porsche', 'Đức'),
                                         (16, 'Suzuki', 'Nhật Bản'),
                                         (17, 'Toyota', 'Nhật Bản'),
                                         (18, 'VinFast', 'Việt Nam'),
                                         (19, 'Volvo', 'Thụy Điển')
    ON CONFLICT (id) DO NOTHING;
INSERT INTO car (id, model, price, discount, manufacture_year, color, description, image_url, stock_quantity, brand_id) VALUES
                                                                                                                            (1, 'A5 Sportback', 959000000, 0.1, 2017, 'Trắng', 'Audi A5 2017. Xe trắng/ Nội thất đen, siêu mới siêu keng. Zin chuẩn từ A - Z. Cam kết xe đạt tiêu chuẩn không đâm đụng, không ngập nước, máy & hộp số Zin nguyên bản. ', 'car_images/1_a5sportback.jpeg', 5, 1),
                                                                                                                            (2, 'Q5 45 TFSI', 1580000000, 0, 2022, 'Trắng', 'Audi Q5 Sline 45TFSI Quattro Model 2022. Lăn bánh được 36.000 km, bảo dưỡng chính hãng đầy đủ lịch sử. Dán keo ppf nguyên xe. Body Sline, mâm 19 "(bản đặc biệt nhiều options). Ghế Sline, Da Alcantara, cửa hích, trần sao, camera hành trình. HUD, Tự de, loa B&O, màn hình Audi Vitual Cockpit, Apple carplay, Đèn Ambient light, Matrix Led, Cốp điện.', 'car_images/2_q545tfsi.jpeg', 4, 1),
                                                                                                                            (3, 'A6 45 TFSI', 1290000000, 0.07, 2020, 'Nâu', 'Audi A6 2020. Đỉnh cao công nghệ & đẳng cấp doanh nhân. Cảm biến áp suất lốp, Apple carplay, Cảnh báo điểm mù, Ppf nội thất xịn... Đẹp không lỗi nhỏ.', 'car_images/3_a645tfsi.jpeg', 2, 1),
                                                                                                                            (4, '320i Excecutive', 539000000, 0.09, 2016, 'Đen', 'BMW 320i Executive 2016. Đậm chất thể thao & đẳng cấp đích thực. Màn hình iDrive sắc nét, Vô lăng bọc da bám tay, Cảm biến quanh xe, Film cách nhiệt xịn xò... Xe cọp giữ gìn, cam kết không lỗi nhỏ.', 'car_images/4_320iexecutive.jpeg', 5, 2),
                                                                                                                            (5, '330i M Sport', 1399000000, 0, 2022, 'Trắng', 'BMW 330i M Sport 2022. Chiếc sedan thể thao quốc dân của nhà BMW – vừa giữ được chất lái phấn khích, vừa đảm bảo sự sang trọng và tiện nghi cho nhu cầu sử dụng hằng ngày. Form MSport mạnh mẽ, nội thất da lộn hiếm – nhìn là mê, lái là. Nội thất: Đen da lộn full xe. Trang bị MSport thể thao – vô lăng M, bodykit M, mâm M cực đẹp. Động cơ 2.0 Turbo mạnh mẽ – cảm giác lái chuẩn BMW.', 'car_images/5_330imsport.jpeg', 3, 2),
                                                                                                                            (6, '320i Sport Line', 1439000000, 0.1, 2024, 'Trắng', 'BMW 320i Sport Line 2024. Sự giao thoa hoàn hảo giữa tốc độ & sự lịch lãm. Kết nối Apple Carplay, Hệ thống âm thanh sống động, Camera lùi siêu nét, Nước sơn zin căng bóng... Hoàn hảo đến từng chi tiết nhỏ nhất.', 'car_images/6_320isportline.jpeg', 4, 2),
                                                                                                                            (7, 'Captiva LT MT', 239000000, 0, 2010, 'Xanh biển', 'Chevrolet Captiva LT MT 2010. Bản hiếm gặp. Được trang bị màn hình Androi, camera hành trình, 2 túi khí, phanh ABS chống trơn chống trượt. Xe gầm cao, 7 chỗ rất tiện lợi để đi chuyển và phục vụ nhu cầu của gia đình.', 'car_images/7_captivaltmt.jpeg', 4, 3),
                                                                                                                            (8, 'Captiva Revv LTZ 2.4 AT', 205000000, 0.1, 2010, 'Trắng', 'Chevrolet Captiva LTZ 2.4AT 2010. SUV 7 chỗ đa dụng & đậm chất cơ bắp Mỹ. Ghế lái chỉnh điện, điều hòa tự động mát lạnh, nội thất da êm ái, gương cụp xòe... Khung gầm cực đầm chắc, bao test lỗi toàn quốc.', 'car_images/8_captivarevvltz.jpeg', 3, 3),
                                                                                                                            (9, 'Everest', 279000000, 0, 2009, 'Đen', 'Ford Everest 2009. Chiến binh đường trường & Đỉnh cao thực dụng. Máy dầu TDCi cực tiết kiệm, gầm cao máy thoáng, la-zăng đúc thể thao, bệ bước chân to bản... Xe gia đình giữ gìn, gầm bệ chắc nịch không một lỗi nhỏ.', 'car_images/9_everest.jpeg', 4, 4),
                                                                                                                            (10, 'Tourneo Titanium', 648000000, 0, 2019, 'Đen', 'Ford Tourneo Titanium 2019. Chuyên cơ mặt đất & Đẳng cấp thương gia. Hệ thống treo khí nén siêu êm, Ghế VIP độc lập, Cửa sổ trời hiện đại, Màn hình SYNC 3 thông minh... Xe đi cực giữ gìn, đẹp xuất sắc không một lỗi nhỏ.', 'car_images/10_tourneotitanium.jpeg', 1, 4),
                                                                                                                            (11, 'CR-V', 500000000, 0, 2015, 'Trắng', 'Honda CR-V 2015. Biểu tượng bền bỉ & Lựa chọn vàng cho gia đình. Nút bấm Start/Stop, Chế độ Eco siêu tiết kiệm, Ghế lái chỉnh điện, Cruise Control nhàn hạ... Đẹp xuất sắc không một lỗi nhỏ.', 'car_images/11_crv.jpeg', 5, 5),
                                                                                                                            (12, 'City 1.5 TOP CVT', 379000000, 0, 2019, 'Trắng', 'Honda City 1.5 TOP 2019. Bền bỉ thực dụng & Cảm giác lái lanh lẹ. Đề nổ Start/Stop, Màn hình giải trí sắc nét, Camera lùi góc rộng, Dán film cách nhiệt xịn xò... Gầm bệ chắc nịch, cam kết máy số zin mượt mà.', 'car_images/12_citytopcvt.jpeg', 5, 5),
                                                                                                                            (13, 'Grand Starex 2.4 MT', 430000000, 0, 2016, 'Trắng', 'Hyundai Grand Starex 2.4 MT 2016. Ông vua không gian & Cỗ máy sinh lời đích thực. Không gian thênh thang, Cửa lùa 2 bên tiện dụng, Điều hòa 2 dàn lạnh buốt, Trải sàn da sạch sẽ... Máy số zin êm ái, gầm bệ chắc nịch sẵn sàng cày ải.', 'car_images/13_grandstarex.jpeg', 4, 6),
                                                                                                                            (14, 'Creta 1.5L Đặc biệt', 565000000, 0, 2022, 'Trắng', 'Hyundai Creta 1.5L Đặc biệt 2022. Trẻ trung cá tính & Ngập tràn tiện nghi. Cruise Control nhàn hạ, Camera lùi góc rộng siêu nét, Cửa gió điều hòa ghế sau, Chìa khóa thông minh Start/Stop... Máy số êm ái, bao check hãng toàn quốc', 'car_images/14_creta.jpeg', 1, 6),
                                                                                                                            (15, 'Tucson 2.0 Đặc biệt', 790000000, 0, 2023, 'Đen', 'Hyundai Tucson 2.0 Đặc biệt 2023. Rộng rãi vô địch & Trải nghiệm lái khác biệt. Ghế lái chỉnh điện đa hướng, Điều hòa 2 vùng độc lập, Camera 360 sắc nét, Cảm biến áp suất lốp... Xe lướt cọp, sơn zin gần như cả xe.', 'car_images/15_tucson.jpeg', 1, 6),
                                                                                                                            (16, 'mu-X', 785000000, 0.07, 2023, 'Trắng', 'Isuzu mu-X 2023. Đỉnh cao thực dụng & Bền bỉ vô đối. Máy dầu 1.9L siêu tiết kiệm, Gói an toàn ADAS cao cấp, Màn hình giải trí 9 inch, Phanh tay điện tử... Chất xe lướt nguyên bản, sẵn sàng đồng hành cùng gia đình trên mọi nẻo đường.', 'car_images/16_mux.jpeg', 2, 7),
                                                                                                                            (17, 'D-Max LS PRESTIGE 1.9 4x2 MT', 479000000, 0.09, 2023, 'Xám bạc', 'Isuzu D-Max LS Prestige 1.9 MT 2023. Tối ưu chi phí & Thu hồi vốn cực nhanh. Phanh ABS/EBD an toàn, Vô lăng tích hợp phím, Nội thất sạch sẽ, Dán film cách nhiệt cao cấp... Chất xe nguyên bản 100%, sẵn sàng hồ sơ sang tên ngay trong ngày.', 'car_images/17_dmaxprestige.jpeg', 1, 7),
                                                                                                                            (18, 'Morning S 1.25 AT', 295000000, 0, 2019, 'Đỏ', 'Kia Morning S 1.25 AT 2019. Nhỏ gọn thể thao & Vua luồn lách phố thị. Bản S kịch nóc với bô đôi cá tính, đèn Bi-Projector siêu sáng, màn hình DVD tích hợp cam lùi, điều hòa tự động mát sâu... Xe gia đình đi phố cực lướt, cam kết máy zin keo chỉ nguyên bản.', 'car_images/18_morningsat.jpeg', 3, 8),
                                                                                                                            (19, 'Morning 1.0MT', 76000000, 0, 2012, 'Xám', 'Kia Morning 1.0 MT 2012. Nồi đồng cối đá & Lựa chọn khởi nghiệp siêu tiết kiệm. Máy 1.0L ăn xăng như ngửi, Côn số mượt mà, Điều hòa mát lạnh, La-zăng đúc chắc chắn... Xe cứng cáp sẵn sàng cày ải, anh em rước về thu hồi vốn cực nhanh.', 'car_images/19_morningmt.jpeg', 2, 8),
                                                                                                                            (20, 'Sportage 1.6 T Signature X-line AWD', 799000000, 0, 2022, 'Đỏ', 'Kia Sportage 1.6T Signature X-line AWD 2022. Thiết kế tương lai & Ngập tràn công nghệ. Động cơ 1.6 Turbo mạnh mẽ, Cần số điện tử dạng núm xoay, Màn hình kép cong 12.3 inch, Hệ thống 8 loa Harman Kardon đỉnh cao... Xe lướt giữ gìn cẩn thận, bảo dưỡng full lịch sử hãng, cam kết chất lượng bằng văn bản cho anh em yên tâm xuống tiền.', 'car_images/20_sportageawd.jpeg', 5, 8),
                                                                                                                            (21, 'Range Rover Evoque', 499000000, 0, 2012, 'Trắng', 'Land Rover Range Rover Evoque 2012. Biểu tượng thời trang & Đẳng cấp Hoàng gia Anh. Âm thanh Meridian đỉnh cao, Cửa sổ trời toàn cảnh Panorama, Cần số núm xoay thò thụt độc đáo, Nội thất da cao cấp... Form dáng sành điệu vượt thời gian, cam kết chất xe nguyên bản không đâm đụng bơi lội.', 'car_images/21_rangerovereroque.jpeg', 2, 9),
                                                                                                                            (22, 'Range Rover Autobiography LWB 5.0 V8', 2386000000, 0.06, 2014, 'Đen', 'Range Rover Autobiography LWB 5.0 V8 2014. Chuyên cơ mặt đất & Đẳng cấp của giới tinh hoa. Trục cơ sở dài thênh thang, Ghế VIP massage/sưởi/làm mát, Hệ thống âm thanh vòm Meridian đỉnh cao, Cửa hít tự động... Siêu phẩm một thời vạn người mê, chất xe giữ gìn cẩn thận bao check test toàn quốc cho các Chủ tịch.', 'car_images/22_rangeroverautobiography.jpeg', 5, 9),
                                                                                                                            (23, 'ES 350', 1050000000, 0, 2015, 'Đen', 'Lexus ES 350 2015. Sedan hạng sang & Biểu tượng giữ giá. Điều hòa đa vùng lạnh buốt, Chìa khóa thông minh, Cảm biến quanh xe, Nội thất ốp gỗ tinh tế... Trải nghiệm xe sang đẳng cấp với chi phí nuôi rẻ như xe cỏ, hồ sơ cầm tay sang tên trong một nốt nhạc.', 'car_images/23_es350.jpeg', 3, 10),
                                                                                                                            (24, 'LX 570 Super Sport', 1490000000, 0.06, 2009, 'Đỏ', 'Lexus LX 570 2009 up Super Sport. Chuyên cơ mặt đất & Lột xác hoàn hảo. Lên form Super Sport hầm hố, Động cơ V8 5.7L uy lực, Nâng hạ gầm êm ái, Dàn âm thanh Mark Levinson đỉnh cao... Ngoại hình chục tỷ nhưng giá rước về chỉ bằng chiếc SUV cỡ trung, tự tin bao check hãng toàn quốc.', 'car_images/24_lx570supersport.jpeg', 2, 10),
                                                                                                                            (25, 'CX-5 2.0 Luxury', 745000000, 0, 2023, 'Đỏ', 'Mazda CX-5 2.0 Luxury 2023. Tuyệt tác Kodo & Gầm cao quốc dân. Gói an toàn i-Activsense thông minh, Hiển thị tốc độ HUD, Cốp điện rảnh tay, Màn hình Apple Carplay sắc nét... Xe lướt đẹp như đập hộp, bao check test đâm đụng, ngập nước toàn quốc.', 'car_images/25_cx5luxury.jpeg', 4, 11),
                                                                                                                            (26, 'CX-8 Luxury', 718000000, 0, 2020, 'Đỏ', 'Mazda CX-8 Luxury 2020. Gầm cao bệ vệ & Ngập tràn công nghệ tiện nghi. Cruise Control nhàn hạ, Chìa khóa thông minh, La-zăng đúc 19 inch thể thao, Dán film cách nhiệt xịn xò... Gầm bệ đầm chắc không tiếng động lạ, tự tin ra lộc cực mạnh cho bác nào cầm tiền tươi chốt nhanh.', 'car_images/26_cx8luxury.jpeg', 3, 11),
                                                                                                                            (27, '3 Sport 2.0L Signature Luxury', 495000000, 0, 2019, 'Trắng', 'Mazda 3 Sport 2.0L Signature Luxury 2019. Trải nghiệm phấn khích & Đẳng cấp thời trang. Chế độ lái Sport uy lực, Gương chống chói tự động, La-zăng đúc 18 inch xám khói, Dán film cách nhiệt xịn... Chất xe hoàn hảo đến từng chi tiết, pháp lý chuẩn chỉ sẵn sàng sang tên trong chớp mắt.', 'car_images/27_sportluxury.jpeg', 2, 11),
                                                                                                                            (28, 'C300 AMG', 338000000, 0, 2014, 'Đỏ', 'Mercedes-Benz C300 AMG 2014. Uy lực dẫn đầu & Đậm chất thể thao. Bodykit AMG hầm hố, Cửa sổ trời toàn cảnh, Vô lăng D-cut bọc da nappa, La-zăng thể thao AMG... Chất xe cọp hiếm có, cỗ máy V6 (hoặc I4 Turbo) nguyên bản gầm rú uy lực, bao check hãng toàn quốc.', 'car_images/28_c300amg.jpeg', 4, 12),
                                                                                                                            (29, 'E200 E200', 820000000, 0.09, 2018, 'Trắng', 'Mercedes-Benz E200 2018. Tiểu S-Class hào hoa & Đẳng cấp doanh nhân thành đạt. Đèn viền nội thất Ambient Light 64 màu, Ốp gỗ tần bì vân sần tinh tế, Đèn High Performance siêu sáng, Apple Carplay mượt mà... Xe Chủ tịch đi giữ gìn cực kỳ cẩn thận, sơn zin căng bóng bao check test bất kỳ đại lý Mercedes nào trên toàn quốc.', 'car_images/29_e200e200.jpeg', 4, 12),
                                                                                                                            (30, 'C200 2.0 AT', 699000000, 0.1, 2017, 'Xanh biển', 'Mercedes-Benz C200 2.0 AT 2017. Trải nghiệm êm ái & Đậm chất xe sang Đức. Động cơ 2.0L tăng áp mượt mà, Hệ thống treo Agility Control trứ danh, Ghế da chỉnh điện nhớ vị trí, Cách âm chống ồn đỉnh cao... Máy số đại chất êm như hơi thở, tự tin mời anh em dẫn theo thợ ruột chuyên Mercedes đến thẩm định thoải mái.', 'car_images/30_c200at.jpeg', 4, 12),
                                                                                                                            (31, 'Triton Athlete 4x2 AT', 625000000, 0, 2022, 'Đỏ', 'Mitsubishi Triton Athlete 4x2 AT 2022. Bán tải thể thao & Đậm chất cá tính. Gói ngoại thất Athlete đen nhám cực ngầu, Nội thất bọc da Cam-Đen phong cách, Đèn Bi-LED sắc sảo, Lẫy chuyển số vô lăng... Sơn zin căng bóng nguyên bản, anh em rước về đi công trình, đi cafe hay dạo phố đều thu hút mọi ánh nhìn.', 'car_images/31_tritonathlete.jpeg', 4, 13),
                                                                                                                            (32, 'Xpander 1.5 AT', 615000000, 0.08, 2024, 'Trắng', 'Mitsubishi Xpander 1.5 AT 2024. Vua MPV 7 chỗ & Rộng rãi vô địch. Khoảng sáng gầm 225mm vượt mọi địa hình, Phanh tay điện tử Auto Hold nhàn nhã, Điều hòa 2 dàn lạnh sâu, Cụm đèn T-Shape siêu sáng... Xe siêu lướt vẫn vương vấn mùi mới, bảo hành chính hãng còn miên man, các bác rước về vi vu xuyên Việt cùng gia đình cực kỳ an tâm.', 'car_images/32_xpanderat.jpeg', 5, 13),
                                                                                                                            (33, 'X trail 2.5 SV 4WD Premium', 625000000, 0, 2020, 'Xám', 'Nissan X-Trail 2.5 SV 4WD Premium 2020. Crossover 5+2 đa dụng & Ngập tràn công nghệ. Ghế da không trọng lực Zero Gravity siêu êm, Cốp điện đá chân rảnh tay, Cảnh báo điểm mù an toàn, Cảm biến va chạm quanh xe... Nội thất da cao cấp giữ gìn cẩn thận, tự tin bao mang ra bất kỳ đại lý Nissan nào trên toàn quốc để check đâm đụng, ngập nước.', 'car_images/33_xtrailpremium.jpeg', 5, 14),
                                                                                                                            (34, 'Terra 2.5L V 4WD AT', 680000000, 0, 2019, 'Xanh biển', 'Nissan Terra 2.5L V 4WD AT 2019. Chiến thần địa hình & SUV 7 chỗ đích thực. Hệ dẫn động 4 bánh có khóa vi sai, Khung gầm hộp kín siêu cứng cáp, Camera 360 độ quanh xe, Cảnh báo chệch làn đường... Gầm bệ sáng choang không một vết xước, anh em rước về cày đèo lội suối hay đi dã ngoại đều vô đối trong tầm giá.', 'car_images/34_terra4wd.jpeg', 4, 14),
                                                                                                                            (35, 'Cayenne Platinum Edition', 4555000000, 0, 2022, 'Đen', 'Porsche Cayenne Platinum Edition 2022. Phiên bản đặc biệt & Đậm chất thể thao sang trọng. Điểm nhấn sơn Satin Platinum độc quyền, Mâm 21-inch RS Spyder Design trứ danh, Cửa sổ trời toàn cảnh Panorama, Logo Porsche dập nổi trên tựa đầu... Siêu phẩm lướt cực mới, pháp lý chuẩn chỉ, sẵn sàng giao xe bằng xe lồng đến tận gara cho các Chủ tịch đam mê tốc độ.', 'car_images/35_cayenneplatinum.jpeg', 4, 15),
                                                                                                                            (36, '911 Carrera', 6679000000, 0, 2021, 'Vàng', 'Porsche 911 Carrera 2021. Huyền thoại tốc độ & Biểu tượng vượt thời gian. Động cơ Boxer 3.0L Twin-Turbo bốc lửa, Hộp số PDK 8 cấp trứ danh sang số chớp mắt, Dải đèn hậu LED liền mạch quyến rũ, Thiết kế thân rộng Widebody bệ vệ... Cỗ máy gầm rú uy lực khơi gợi mọi giác quan, xe siêu lướt cọp sẵn sàng giao bằng xe lồng đến tận cửa cho các Chủ tịch đam mê.', 'car_images/36_911carrera.jpeg', 1, 15),
                                                                                                                            (37, 'XL7 1.5L', 445000000, 0.08, 2022, 'Đen', 'Suzuki XL7 1.5L 2022. Cỗ máy cày ải & Sinh lời cực nhanh. Động cơ 1.5L ăn xăng như ngửi, Gầm thoáng sẵn sàng leo lề, Chi phí bảo dưỡng rẻ như xe máy, Vô lăng D-cut thể thao... Gầm bệ sát xi chắc nịch không một tiếng kêu, sẵn sàng hỗ trợ rút hồ sơ cái rụp cho bác nào cầm tiền tươi đến chốt.', 'car_images/37_xl15l.jpeg', 3, 16),
                                                                                                                            (38, 'Grand vitara 2.0 AT', 155000000, 0, 2003, 'Xanh biển', 'Suzuki Grand Vitara 2.0 AT 2003. Chiến thần địa hình & Nồi đồng cối đá. Động cơ 2.0L siêu bền bỉ, Hệ dẫn động 2 cầu (4x4) gài cầu cơ trứ danh, Hộp số tự động đi phố nhàn hạ, Khung gầm rời cứng cáp... Chất xe cọp hiếm hoi sót lại, anh em rước về cày đèo lội suối hay độ lên đi camping dã ngoại thì hết bài.', 'car_images/38_grandvitara.jpeg', 3, 16),
                                                                                                                            (39, 'Super Carry Van Blind Van', 180000000, 0, 2020, 'Trắng', 'Suzuki Blind Van 2020. Vua luồn lách ngõ hẻm & Đặc quyền chạy phố 24/24. Tải trọng chuẩn quy định không lo cấm giờ, Cửa lùa 2 bên bốc dỡ hàng siêu tiện, Động cơ 1.0L ăn xăng như ngửi, Cabin thiết kế tối ưu... Thùng bệ vuông vắn không một vết móp méo, anh em rước về chỉ việc đổ xăng là cắm mặt cày tiền ngay lập tức.', 'car_images/39_supercarryvan.jpeg', 3, 16),
                                                                                                                            (40, 'Camry 2.4G', 329000000, 0, 2010, 'Đen', 'Toyota Camry 2.4G 2010. Đỉnh cao giữ giá & Vận hành hoàn hảo. Form dáng thanh lịch không lỗi mốt, Vô lăng 4 chấu bọc da tích hợp phím, Gương kính gập điện tự động, Đèn pha tự động sáng... Máy số đại chất thì thầm như thở, gầm bệ đầm chắc không tiếng động lạ, lộc lá ngập tràn cho anh em nào thiện chí cầm tiền tươi qua chốt cọc.', 'car_images/40_camry24g.jpeg', 4, 17),
                                                                                                                            (41, 'Alphard Executive Lounge', 3050000000, 0, 2019, 'Đen', 'Toyota Alphard Executive Lounge 2019. Chuyên cơ mặt đất & Đỉnh cao vị thế. Hàng ghế thương gia VIP Ottoman chỉnh điện có sưởi/làm mát, Da Semi-Aniline thủ công cao cấp, Dàn âm thanh 17 loa JBL trứ danh, Cửa sổ trời kép sang trọng... Siêu phẩm lăn bánh cực ít và giữ gìn cẩn thận, cam kết chất lượng tuyệt đối bằng văn bản, sẵn sàng giao xe bằng xe lồng đến tận biệt thự cho các Chủ tịch.', 'car_images/41_alphardexecutive.jpeg', 1, 17),
                                                                                                                            (42, 'Fadil Tiêu Chuẩn', 265000000, 0, 2019, 'Trắng', 'VinFast Fadil Tiêu Chuẩn 2019. Vua phân khúc hạng A & Vận hành vô đối. Động cơ 1.4L bốc nhất phân khúc đạp là dính ghế, Khung gầm châu Âu cực kỳ đầm chắc khi đi cao tốc, Hộp số vô cấp CVT mượt mà, Hệ thống cân bằng điện tử (ESC) an toàn... Xe zin từng con ốc, keo chỉ nguyên bản 100%, anh em cứ mạnh dạn dẫn thợ qua test thoải mái, sai cam kết em chịu toàn bộ chi phí đi lại.', 'car_images/42_fadil.jpeg', 2, 18),
                                                                                                                            (43, 'VF 3', 209000000, 0.05, 2024, 'Xanh biển', 'VinFast VF 3 2024. Tiểu G-Class chốt phố & Biểu tượng phong cách. Form dáng vuông vức cực ngầu, Gầm cao 191mm tự tin leo lề lội nước, Màu sơn trendy thu hút mọi ánh nhìn, Màn hình giải trí 10 inch siêu mượt... Xe lướt keng như đập hộp, bỏ qua ngay danh sách chờ dài dằng dặc của hãng, anh em chốt là em hỗ trợ giao xe tận cửa trong ngày.', 'car_images/43_vf3.jpeg', 4, 18),
                                                                                                                            (44, 'LUX A2.0 Tiêu chuẩn', 515000000, 0, 2022, 'Đỏ', 'VinFast LUX A2.0 Tiêu chuẩn 2022. Nồi đồng cối đá & Ngập tràn an toàn. Khung gầm dập nguyên khối siêu cứng cáp, Phanh tay điện tử, Cân bằng điện tử chống lật, Camera lùi sắc nét... Bỏ ra số tiền chỉ bằng chiếc Accent mà được vần vô lăng khung gầm BMW xịn xò, pháp lý cá nhân minh bạch hỗ trợ sang tên bấm biển thần tốc trong một nốt nhạc.', 'car_images/44_lux.jpeg', 2, 18),
                                                                                                                            (45, 'XC90', 3150000000, 0, 2022, 'Đen', 'Volvo XC90 2022. Tuyệt tác Scandinavian & Đẳng cấp tinh tế giấu kín. Dàn loa vòm Bowers & Wilkins hay nhất thế giới xe, Cần số pha lê Orrefors chế tác thủ công, Ghế da Nappa đục lỗ cao cấp có massage/làm mát, Cửa sổ trời toàn cảnh Panorama... Nội ngoại thất keng xà beng còn vương vấn mùi da thượng hạng, tự tin mời chuyên gia từ bất kỳ đại lý Volvo nào đến thẩm định, phát hiện lỗi nhỏ em xin biếu luôn xe.', 'car_images/45_xc90.jpeg', 5, 19),
                                                                                                                            (46, 'S90', 1699000000, 0, 2022, 'Trắng', 'Volvo S90 LWB Ultimate MỚI 100%. Tiểu chuyên cơ Bắc Âu & Đặc quyền đập hộp nguyên đai nguyên kiện. Trục cơ sở kéo dài thênh thang, Dàn âm thanh Bowers & Wilkins 19 loa đỉnh cao nhất thế giới xe, Cần số pha lê Orrefors Thụy Điển chế tác thủ công, Bảng điều khiển VIP hàng ghế sau... Xe sẵn giao ngay đủ màu không cần chờ đợi, hỗ trợ lái thử tận nhà và giao xe bằng xe lồng chuyên dụng đến tận biệt thự cho các Chủ tịch.', 'car_images/46_s90.jpeg', 1, 19),
                                                                                                                            (47, 'S90 ultimate', 1579000000, 0.07, 2022, 'Đen', 'Volvo S90 Ultimate 2022. Pháo đài an toàn & Kiệt tác Scandinavian. Khung thép Boron siêu cứng cáp, Gói an toàn chủ động Pilot Assist trứ danh, Ghế da Nappa đục lỗ cao cấp có sưởi/làm mát/massage, Hệ thống lọc không khí Clean Zone trong trẻo... Chiếc xe hoàn hảo để bảo vệ những người thân yêu, sơn zin căng bóng nguyên bản, sẵn sàng giao xe bằng xe lồng đến tận biệt thự cho các bác bận rộn.', 'car_images/47_s90ultimate.jpeg', 1, 19)
    ON CONFLICT (id) DO NOTHING;

INSERT INTO car_images_sub (id, car_id, sort_order, image_url) VALUES
                                                                   (1, 1, 1, 'car_images_sub/1_1.jpeg'),
                                                                   (2, 1, 2, 'car_images_sub/1_2.jpeg'),
                                                                   (3, 1, 3, 'car_images_sub/1_3.jpeg'),
                                                                   (4, 2, 1, 'car_images_sub/2_1.jpeg'),
                                                                   (5, 2, 2, 'car_images_sub/2_2.jpeg'),
                                                                   (6, 2, 3, 'car_images_sub/2_3.jpeg'),
                                                                   (7, 3, 1, 'car_images_sub/3_1.jpeg'),
                                                                   (8, 3, 2, 'car_images_sub/3_2.jpeg'),
                                                                   (9, 3, 3, 'car_images_sub/3_3.jpeg'),
                                                                   (10, 4, 1, 'car_images_sub/4_1.jpeg'),
                                                                   (11, 4, 2, 'car_images_sub/4_2.jpeg'),
                                                                   (12, 4, 3, 'car_images_sub/4_3.jpeg'),
                                                                   (13, 5, 1, 'car_images_sub/5_1.jpeg'),
                                                                   (14, 5, 2, 'car_images_sub/5_2.jpeg'),
                                                                   (15, 5, 3, 'car_images_sub/5_3.jpeg'),
                                                                   (16, 6, 1, 'car_images_sub/6_1.jpeg'),
                                                                   (17, 6, 2, 'car_images_sub/6_2.jpeg'),
                                                                   (18, 6, 3, 'car_images_sub/6_3.jpeg'),
                                                                   (19, 7, 1, 'car_images_sub/7_1.jpeg'),
                                                                   (20, 7, 2, 'car_images_sub/7_2.jpeg'),
                                                                   (21, 7, 3, 'car_images_sub/7_3.jpeg'),
                                                                   (22, 8, 1, 'car_images_sub/8_1.jpeg'),
                                                                   (23, 8, 2, 'car_images_sub/8_2.jpeg'),
                                                                   (24, 8, 3, 'car_images_sub/8_3.jpeg'),
                                                                   (25, 9, 1, 'car_images_sub/9_1.jpeg'),
                                                                   (26, 9, 2, 'car_images_sub/9_2.jpeg'),
                                                                   (27, 9, 3, 'car_images_sub/9_3.jpeg'),
                                                                   (28, 10, 1, 'car_images_sub/10_1.jpeg'),
                                                                   (29, 10, 2, 'car_images_sub/10_2.jpeg'),
                                                                   (30, 10, 3, 'car_images_sub/10_3.jpeg'),
                                                                   (31, 11, 1, 'car_images_sub/11_1.jpeg'),
                                                                   (32, 11, 2, 'car_images_sub/11_2.jpeg'),
                                                                   (33, 11, 3, 'car_images_sub/11_3.jpeg'),
                                                                   (34, 12, 1, 'car_images_sub/12_1.jpeg'),
                                                                   (35, 12, 2, 'car_images_sub/12_2.jpeg'),
                                                                   (36, 12, 3, 'car_images_sub/12_3.jpeg'),
                                                                   (37, 13, 1, 'car_images_sub/13_1.jpeg'),
                                                                   (38, 13, 2, 'car_images_sub/13_2.jpeg'),
                                                                   (39, 13, 3, 'car_images_sub/13_3.jpeg'),
                                                                   (40, 14, 1, 'car_images_sub/14_1.jpeg'),
                                                                   (41, 14, 2, 'car_images_sub/14_2.jpeg'),
                                                                   (42, 14, 3, 'car_images_sub/14_3.jpeg'),
                                                                   (43, 15, 1, 'car_images_sub/15_1.jpeg'),
                                                                   (44, 15, 2, 'car_images_sub/15_2.jpeg'),
                                                                   (45, 15, 3, 'car_images_sub/15_3.jpeg'),
                                                                   (46, 16, 1, 'car_images_sub/16_1.jpeg'),
                                                                   (47, 16, 2, 'car_images_sub/16_2.jpeg'),
                                                                   (48, 16, 3, 'car_images_sub/16_3.jpeg'),
                                                                   (49, 17, 1, 'car_images_sub/17_1.jpeg'),
                                                                   (50, 17, 2, 'car_images_sub/17_2.jpeg'),
                                                                   (51, 17, 3, 'car_images_sub/17_3.jpeg'),
                                                                   (52, 18, 1, 'car_images_sub/18_1.jpeg'),
                                                                   (53, 18, 2, 'car_images_sub/18_2.jpeg'),
                                                                   (54, 18, 3, 'car_images_sub/18_3.jpeg'),
                                                                   (55, 19, 1, 'car_images_sub/19_1.jpeg'),
                                                                   (56, 19, 2, 'car_images_sub/19_2.jpeg'),
                                                                   (57, 19, 3, 'car_images_sub/19_3.jpeg'),
                                                                   (58, 20, 1, 'car_images_sub/20_1.jpeg'),
                                                                   (59, 20, 2, 'car_images_sub/20_2.jpeg'),
                                                                   (60, 20, 3, 'car_images_sub/20_3.jpeg'),
                                                                   (61, 21, 1, 'car_images_sub/21_1.jpeg'),
                                                                   (62, 21, 2, 'car_images_sub/21_2.jpeg'),
                                                                   (63, 21, 3, 'car_images_sub/21_3.jpeg'),
                                                                   (64, 22, 1, 'car_images_sub/22_1.jpeg'),
                                                                   (65, 22, 2, 'car_images_sub/22_2.jpeg'),
                                                                   (66, 22, 3, 'car_images_sub/22_3.jpeg'),
                                                                   (67, 23, 1, 'car_images_sub/23_1.jpeg'),
                                                                   (68, 23, 2, 'car_images_sub/23_2.jpeg'),
                                                                   (69, 23, 3, 'car_images_sub/23_3.jpeg'),
                                                                   (70, 24, 1, 'car_images_sub/24_1.jpeg'),
                                                                   (71, 24, 2, 'car_images_sub/24_2.jpeg'),
                                                                   (72, 24, 3, 'car_images_sub/24_3.jpeg'),
                                                                   (73, 25, 1, 'car_images_sub/25_1.jpeg'),
                                                                   (74, 25, 2, 'car_images_sub/25_2.jpeg'),
                                                                   (75, 25, 3, 'car_images_sub/25_3.jpeg'),
                                                                   (76, 26, 1, 'car_images_sub/26_1.jpeg'),
                                                                   (77, 26, 2, 'car_images_sub/26_2.jpeg'),
                                                                   (78, 26, 3, 'car_images_sub/26_3.jpeg'),
                                                                   (79, 27, 1, 'car_images_sub/27_1.jpeg'),
                                                                   (80, 27, 2, 'car_images_sub/27_2.jpeg'),
                                                                   (81, 27, 3, 'car_images_sub/27_3.jpeg'),
                                                                   (82, 28, 1, 'car_images_sub/28_1.jpeg'),
                                                                   (83, 28, 2, 'car_images_sub/28_2.jpeg'),
                                                                   (84, 28, 3, 'car_images_sub/28_3.jpeg'),
                                                                   (85, 29, 1, 'car_images_sub/29_1.jpeg'),
                                                                   (86, 29, 2, 'car_images_sub/29_2.jpeg'),
                                                                   (87, 29, 3, 'car_images_sub/29_3.jpeg'),
                                                                   (88, 30, 1, 'car_images_sub/30_1.jpeg'),
                                                                   (89, 30, 2, 'car_images_sub/30_2.jpeg'),
                                                                   (90, 30, 3, 'car_images_sub/30_3.jpeg'),
                                                                   (91, 31, 1, 'car_images_sub/31_1.jpeg'),
                                                                   (92, 31, 2, 'car_images_sub/31_2.jpeg'),
                                                                   (93, 31, 3, 'car_images_sub/31_3.jpeg'),
                                                                   (94, 32, 1, 'car_images_sub/32_1.jpeg'),
                                                                   (95, 32, 2, 'car_images_sub/32_2.jpeg'),
                                                                   (96, 32, 3, 'car_images_sub/32_3.jpeg'),
                                                                   (97, 33, 1, 'car_images_sub/33_1.jpeg'),
                                                                   (98, 33, 2, 'car_images_sub/33_2.jpeg'),
                                                                   (99, 33, 3, 'car_images_sub/33_3.jpeg'),
                                                                   (100, 34, 1, 'car_images_sub/34_1.jpeg'),
                                                                   (101, 34, 2, 'car_images_sub/34_2.jpeg'),
                                                                   (102, 34, 3, 'car_images_sub/34_3.jpeg'),
                                                                   (103, 35, 1, 'car_images_sub/35_1.jpeg'),
                                                                   (104, 35, 2, 'car_images_sub/35_2.jpeg'),
                                                                   (105, 35, 3, 'car_images_sub/35_3.jpeg'),
                                                                   (106, 36, 1, 'car_images_sub/36_1.jpeg'),
                                                                   (107, 36, 2, 'car_images_sub/36_2.jpeg'),
                                                                   (108, 36, 3, 'car_images_sub/36_3.jpeg'),
                                                                   (109, 37, 1, 'car_images_sub/37_1.jpeg'),
                                                                   (110, 37, 2, 'car_images_sub/37_2.jpeg'),
                                                                   (111, 37, 3, 'car_images_sub/37_3.jpeg'),
                                                                   (112, 38, 1, 'car_images_sub/38_1.jpeg'),
                                                                   (113, 38, 2, 'car_images_sub/38_2.jpeg'),
                                                                   (114, 38, 3, 'car_images_sub/38_3.jpeg'),
                                                                   (115, 39, 1, 'car_images_sub/39_1.jpeg'),
                                                                   (116, 39, 2, 'car_images_sub/39_2.jpeg'),
                                                                   (117, 39, 3, 'car_images_sub/39_3.jpeg'),
                                                                   (118, 40, 1, 'car_images_sub/40_1.jpeg'),
                                                                   (119, 40, 2, 'car_images_sub/40_2.jpeg'),
                                                                   (120, 40, 3, 'car_images_sub/40_3.jpeg'),
                                                                   (121, 41, 1, 'car_images_sub/41_1.jpeg'),
                                                                   (122, 41, 2, 'car_images_sub/41_2.jpeg'),
                                                                   (123, 41, 3, 'car_images_sub/41_3.jpeg'),
                                                                   (124, 42, 1, 'car_images_sub/42_1.jpeg'),
                                                                   (125, 42, 2, 'car_images_sub/42_2.jpeg'),
                                                                   (126, 42, 3, 'car_images_sub/42_3.jpeg'),
                                                                   (127, 43, 1, 'car_images_sub/43_1.jpeg'),
                                                                   (128, 43, 2, 'car_images_sub/43_2.jpeg'),
                                                                   (129, 43, 3, 'car_images_sub/43_3.jpeg'),
                                                                   (130, 44, 1, 'car_images_sub/44_1.jpeg'),
                                                                   (131, 44, 2, 'car_images_sub/44_2.jpeg'),
                                                                   (132, 44, 3, 'car_images_sub/44_3.jpeg'),
                                                                   (133, 45, 1, 'car_images_sub/45_1.jpeg'),
                                                                   (134, 45, 2, 'car_images_sub/45_2.jpeg'),
                                                                   (135, 45, 3, 'car_images_sub/45_3.jpeg'),
                                                                   (136, 46, 1, 'car_images_sub/46_1.jpeg'),
                                                                   (137, 46, 2, 'car_images_sub/46_2.jpeg'),
                                                                   (138, 46, 3, 'car_images_sub/46_3.jpeg'),
                                                                   (139, 47, 1, 'car_images_sub/47_1.jpeg'),
                                                                   (140, 47, 2, 'car_images_sub/47_2.jpeg'),
                                                                   (141, 47, 3, 'car_images_sub/47_3.jpeg')
    ON CONFLICT (id) DO NOTHING;

