spring.profiles.active=local

spring.ai.openai.chat.options.model=gemini-2.5-flash
spring.ai.openai.embedding.options.model=gemini-embedding-001

# PG vector
spring.ai.vectorstore.type=pgvector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.index-type=none
spring.ai.vectorstore.pgvector.distance-type=cosine_distance


spring.main.allow-bean-definition-overriding=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.password=${Password-Email}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true